apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-k8s-mongodb
  template:
    metadata:
      labels:
        app: springboot-k8s-mongodb
    spec:
      containers:
        - name: final-springboot-app
          image: final-springboot-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mongodb
            - name: DB_NAME
              value: mydb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mongodb
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
